// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: h3-reference-to-video-turbo-realtime v0.2.0

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  H3ReferenceToVideoTurboRealtimeTracks,
  type H3ReferenceToVideoTurboRealtimeOptions,
  type H3ReferenceToVideoTurboRealtimePopParams,
  type H3ReferenceToVideoTurboRealtimeMoveParams,
  type H3ReferenceToVideoTurboRealtimePlayParams,
  type H3ReferenceToVideoTurboRealtimeEnqueueParams,
  type H3ReferenceToVideoTurboRealtimeSetSeedParams,
  type H3ReferenceToVideoTurboRealtimeSetCanvasParams,
  type H3ReferenceToVideoTurboRealtimeSetAutoplayParams,
  type H3ReferenceToVideoTurboRealtimeSetClipSecondsParams,
  type H3ReferenceToVideoTurboRealtimeSetFlushOnClipEndParams,
  type H3ReferenceToVideoTurboRealtimeMessage,
  type H3ReferenceToVideoTurboRealtimeClipMovedMessage,
  type H3ReferenceToVideoTurboRealtimeClipFailedMessage,
  type H3ReferenceToVideoTurboRealtimeClipPoppedMessage,
  type H3ReferenceToVideoTurboRealtimeClipQueuedMessage,
  type H3ReferenceToVideoTurboRealtimeClipStartedMessage,
  type H3ReferenceToVideoTurboRealtimeClipStoppedMessage,
  type H3ReferenceToVideoTurboRealtimeQueueUpdateMessage,
  type H3ReferenceToVideoTurboRealtimeStateUpdateMessage,
  type H3ReferenceToVideoTurboRealtimeClipFinishedMessage,
  type H3ReferenceToVideoTurboRealtimeCommandErrorMessage,
  type H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage,
  type H3ReferenceToVideoTurboRealtimeSessionResetMessage,
  type H3ReferenceToVideoTurboRealtimeClipGeneratedMessage,
  type H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage,
  type H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage,
  type H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage,
  type H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage,
  type H3ReferenceToVideoTurboRealtimeRecvTrackName,
} from "./h3";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link H3ReferenceToVideoTurboRealtimeProvider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type H3ReferenceToVideoTurboRealtimeProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the H3ReferenceToVideoTurboRealtime model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useH3ReferenceToVideoTurboRealtime} and the `useH3ReferenceToVideoTurboRealtime<Message>` hooks below it.
 */
export function H3ReferenceToVideoTurboRealtimeProvider({
  children,
  ...rest
}: H3ReferenceToVideoTurboRealtimeProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...H3ReferenceToVideoTurboRealtimeTracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the H3ReferenceToVideoTurboRealtime model as typed commands bound to the nearest
 * {@link H3ReferenceToVideoTurboRealtimeProvider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `lastError` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 *
 * Each typed event method resolves with the command's correlated
 * reply: the declared reply message for commands that return one,
 * `undefined` once the handler completes for commands that don't.
 */
export function useH3ReferenceToVideoTurboRealtime() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const lastMessage = useReactor((s) => s.lastMessage);
  const pauseTrack = useReactor((s) => s.pauseTrack);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const resumeTrack = useReactor((s) => s.resumeTrack);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    lastMessage,
    pauseTrack,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    resumeTrack,
    sendCommand,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    pop: async (params: H3ReferenceToVideoTurboRealtimePopParams): Promise<H3ReferenceToVideoTurboRealtimeClipPoppedMessage | undefined> => {
      const reply = await sendCommand("pop", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipPoppedMessage>(reply);
    },
    move: async (params: H3ReferenceToVideoTurboRealtimeMoveParams): Promise<H3ReferenceToVideoTurboRealtimeClipMovedMessage | undefined> => {
      const reply = await sendCommand("move", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipMovedMessage>(reply);
    },
    play: async (params: H3ReferenceToVideoTurboRealtimePlayParams): Promise<undefined> => {
      await sendCommand("play", params);
      return undefined;
    },
    stop: async (): Promise<undefined> => {
      await sendCommand("stop", {});
      return undefined;
    },
    reset: async (): Promise<H3ReferenceToVideoTurboRealtimeSessionResetMessage | undefined> => {
      const reply = await sendCommand("reset", {});
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeSessionResetMessage>(reply);
    },
    enqueue: async (params: H3ReferenceToVideoTurboRealtimeEnqueueParams): Promise<H3ReferenceToVideoTurboRealtimeClipQueuedMessage | undefined> => {
      const reply = await sendCommand("enqueue", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipQueuedMessage>(reply);
    },
    setSeed: async (params: H3ReferenceToVideoTurboRealtimeSetSeedParams): Promise<H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage | undefined> => {
      const reply = await sendCommand("set_seed", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage>(reply);
    },
    getQueue: async (): Promise<H3ReferenceToVideoTurboRealtimeQueueUpdateMessage | undefined> => {
      const reply = await sendCommand("get_queue", {});
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeQueueUpdateMessage>(reply);
    },
    getState: async (): Promise<H3ReferenceToVideoTurboRealtimeStateUpdateMessage | undefined> => {
      const reply = await sendCommand("get_state", {});
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeStateUpdateMessage>(reply);
    },
    setCanvas: async (params: H3ReferenceToVideoTurboRealtimeSetCanvasParams): Promise<H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage | undefined> => {
      const reply = await sendCommand("set_canvas", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage>(reply);
    },
    setAutoplay: async (params: H3ReferenceToVideoTurboRealtimeSetAutoplayParams): Promise<H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage | undefined> => {
      const reply = await sendCommand("set_autoplay", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage>(reply);
    },
    setClipSeconds: async (params: H3ReferenceToVideoTurboRealtimeSetClipSecondsParams): Promise<H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage | undefined> => {
      const reply = await sendCommand("set_clip_seconds", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage>(reply);
    },
    setFlushOnClipEnd: async (params: H3ReferenceToVideoTurboRealtimeSetFlushOnClipEndParams): Promise<H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage | undefined> => {
      const reply = await sendCommand("set_flush_on_clip_end", params);
      return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage>(reply);
    },
  };
}

/**
 * Subscribe to any H3ReferenceToVideoTurboRealtime message with a fully-typed handler.
 * The handler receives a discriminated H3ReferenceToVideoTurboRealtimeMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeMessage(
  handler: (message: H3ReferenceToVideoTurboRealtimeMessage) => void,
): void {
  useReactorMessage((msg: unknown) =>
    handler(_unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg)),
  );
}

/**
 * Subscribe to "clip_moved" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipMovedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipMoved(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipMovedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_moved") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipMovedMessage);
    }
  });
}

/**
 * Subscribe to "clip_failed" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipFailedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipFailed(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipFailedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_failed") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipFailedMessage);
    }
  });
}

/**
 * Subscribe to "clip_popped" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipPoppedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipPopped(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipPoppedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_popped") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipPoppedMessage);
    }
  });
}

/**
 * Subscribe to "clip_queued" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipQueuedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipQueued(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipQueuedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_queued") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipQueuedMessage);
    }
  });
}

/**
 * Subscribe to "clip_started" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipStartedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipStarted(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipStartedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_started") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipStartedMessage);
    }
  });
}

/**
 * Subscribe to "clip_stopped" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipStoppedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipStopped(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipStoppedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_stopped") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipStoppedMessage);
    }
  });
}

/**
 * Subscribe to "queue_update" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeQueueUpdateMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeQueueUpdate(
  handler: (message: H3ReferenceToVideoTurboRealtimeQueueUpdateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "queue_update") {
      handler(m as H3ReferenceToVideoTurboRealtimeQueueUpdateMessage);
    }
  });
}

/**
 * Subscribe to "state_update" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeStateUpdateMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeStateUpdate(
  handler: (message: H3ReferenceToVideoTurboRealtimeStateUpdateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "state_update") {
      handler(m as H3ReferenceToVideoTurboRealtimeStateUpdateMessage);
    }
  });
}

/**
 * Subscribe to "clip_finished" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipFinishedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipFinished(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipFinishedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_finished") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipFinishedMessage);
    }
  });
}

/**
 * Subscribe to "command_error" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeCommandErrorMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeCommandError(
  handler: (message: H3ReferenceToVideoTurboRealtimeCommandErrorMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "command_error") {
      handler(m as H3ReferenceToVideoTurboRealtimeCommandErrorMessage);
    }
  });
}

/**
 * Subscribe to "seed_accepted" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeSeedAccepted(
  handler: (message: H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "seed_accepted") {
      handler(m as H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "session_reset" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeSessionResetMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeSessionReset(
  handler: (message: H3ReferenceToVideoTurboRealtimeSessionResetMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "session_reset") {
      handler(m as H3ReferenceToVideoTurboRealtimeSessionResetMessage);
    }
  });
}

/**
 * Subscribe to "clip_generated" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipGeneratedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipGenerated(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipGeneratedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_generated") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipGeneratedMessage);
    }
  });
}

/**
 * Subscribe to "flush_accepted" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeFlushAccepted(
  handler: (message: H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "flush_accepted") {
      handler(m as H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "canvas_accepted" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeCanvasAccepted(
  handler: (message: H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "canvas_accepted") {
      handler(m as H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "autoplay_accepted" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeAutoplayAccepted(
  handler: (message: H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "autoplay_accepted") {
      handler(m as H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "clip_length_accepted" messages only.
 * Handler receives a fully-typed H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage.
 */
export function useH3ReferenceToVideoTurboRealtimeClipLengthAccepted(
  handler: (message: H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(msg);
    if (m.type === "clip_length_accepted") {
      handler(m as H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `H3ReferenceToVideoTurboRealtimeRecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useH3ReferenceToVideoTurboRealtimeTrack(
  name: H3ReferenceToVideoTurboRealtimeRecvTrackName,
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type H3ReferenceToVideoTurboRealtimeMainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<H3ReferenceToVideoTurboRealtimeProvider>`.
 */
export function H3ReferenceToVideoTurboRealtimeMainVideoView(
  props: H3ReferenceToVideoTurboRealtimeMainVideoViewProps,
): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}
