// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: h3-reference-to-video-turbo-realtime v0.2.0

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "h3-reference-to-video-turbo-realtime" as const;
export const MODEL_VERSION = "v0.2.0" as const;

/**
 * Preset media tracks for the H3ReferenceToVideoTurboRealtime model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const H3ReferenceToVideoTurboRealtimeTracks = [
  { name: "main_video", kind: "video", direction: "recvonly" },
  { name: "main_audio", kind: "audio", direction: "recvonly" },
] as const;

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type H3ReferenceToVideoTurboRealtimeRecvTrackName =
  "main_video"
  | "main_audio";

/** Remove a clip from its queue; reply clip_popped and emit queue_update and state_update. A running build finishes but is discarded. Refuses with command_error for a missing/unknown id. Use stop for the playing clip. */
export interface H3ReferenceToVideoTurboRealtimePopParams {
  /**
   * UUID of the clip to remove from either queue.
   * @default ""
   */

  clip_id?: string;
}

/** Reposition within the current queue, 0 = front. A running build is unaffected. Replies clip_moved and emits queue_update; refuses with command_error for a missing/unknown id or invalid position. */
export interface H3ReferenceToVideoTurboRealtimeMoveParams {
  /**
   * UUID of a queued clip.
   * @default ""
   */

  clip_id?: string;
  /**
   * Position in its current queue; past the end appends.
   * @minimum 0
   * @default 0
   */

  position?: number;
}

/** Play the front ready clip, or a named ready clip. Consumes it and emits clip_started, queue_update and state_update. Refuses with command_error if already playing or no matching ready clip exists. */
export interface H3ReferenceToVideoTurboRealtimePlayParams {
  /**
   * UUID of a ready clip; blank takes the playout front.
   * @default ""
   */

  clip_id?: string;
}

/** Queue a clip with 1–9 reference images at position, or at the back. Each clip keeps its own prompt and ordered references: new images do not alter earlier requests. The images guide appearance, not a fixed first or last frame. Replies clip_queued and broadcasts queue_update and state_update; completion emits clip_generated. Refuses with command_error for empty text, missing/invalid reference, invalid parameters or a full generation queue. */
export interface H3ReferenceToVideoTurboRealtimeEnqueueParams {
  /**
   * Omitted or null uses and advances the default seed. An explicit seed leaves the default unchanged.
   * @minimum 0
   * @default null
   */

  seed?: number | null;
  /**
   * What the clip should show and sound like, up to 12000 characters; stored unchanged.
   * @maxLength 12000
   * @default ""
   */

  prompt?: string;
  /**
   * Requested duration between 5 and 15.084 seconds, rounded to frames then aligned upward to a supported length. Actual output ranges from 5.167 to 15.083 seconds. Null uses the session default.
   * @minimum 5
   * @maximum 15.084
   * @default null
   */

  seconds?: number | null;
  /**
   * Opaque client string, up to 2000 characters, echoed unchanged with the clip.
   * @maxLength 2000
   * @default ""
   */

  metadata?: string;
  /**
   * Generation queue position: 0 is the next build; omitted or past the end appends. The running build is unaffected.
   * @minimum 0
   * @default null
   */

  position?: number | null;
  /**
   * One JPEG, PNG or WebP reference for this clip. Guides subjects and appearance, not a keyframe. Supply this or reference_images, not both.
   * @default null
   */

  reference_image?: FileRef | null;
  /**
   * Ordered list of 1–9 uploaded JPEG, PNG or WebP references. In the prompt, Picture 1 names the first image, Picture 2 the second, and so on. Supply this or reference_image, not both. Each clip retains its own list, including while other clips build or play.
   * @default null
   */

  reference_images?: FileRef[] | null;
  /**
   * UUID of a generated clip to continue temporally from: this clip's motion, camera and audio carry across the boundary while its own references still drive appearance. Blank for an independent clip. The source must have finished generating; unknown or dropped ids fall back to an independent clip.
   * @default ""
   */

  continue_from_clip_id?: string;
}

/** Set the advancing default seed for future enqueues. Replies seed_accepted and emits state_update; an invalid seed emits command_error. Explicit per-clip seeds do not advance it. */
export interface H3ReferenceToVideoTurboRealtimeSetSeedParams {
  /**
   * Nonnegative default seed; queued clips keep their seeds.
   * @minimum 0
   * @default 1000
   */

  seed?: number;
}

/** Set the canvas while both queues and playback are empty. Replies canvas_accepted and emits state_update; refuses with command_error for an unsupported aspect or nonempty session. */
export interface H3ReferenceToVideoTurboRealtimeSetCanvasParams {
  /**
   * Choose 16:9 (1344x768), 1:1 (768x768), 9:16 (768x1344), or 4:3 (1024x768).
   * @default "16:9"
   */

  aspect?: "16:9" | "1:1" | "9:16" | "4:3";
}

/** Automatically play ready clips whenever idle. Empty queues wait; no prompts are generated automatically. Replies autoplay_accepted and emits state_update. */
export interface H3ReferenceToVideoTurboRealtimeSetAutoplayParams {
  /**
   * True plays the ready queue; false waits for play after each clip.
   * @default false
   */

  enabled?: boolean;
}

/** Set the duration for future enqueues, aligned to a supported frame count. Replies clip_length_accepted and emits state_update; invalid lengths emit command_error. Queued clips keep their lengths. */
export interface H3ReferenceToVideoTurboRealtimeSetClipSecondsParams {
  /**
   * Requested duration between 5 and 15.084 seconds, rounded to frames then aligned upward to a supported length. The reply reports actual duration and frame count.
   * @minimum 5
   * @maximum 15.084
   * @default 15
   */

  seconds?: number;
}

/** Choose black or a held last frame at boundaries. Off carries the playback clock across ready autoplay clips without flushing. Does not guarantee visual continuity; reset always clears tracks. Replies flush_accepted and emits state_update. */
export interface H3ReferenceToVideoTurboRealtimeSetFlushOnClipEndParams {
  /**
   * True flushes to black; false holds the last frame and avoids flushing between autoplay clips.
   * @default true
   */

  enabled?: boolean;
}

/** Emitted as the correlated reply when move changes queue order. */
export interface H3ReferenceToVideoTurboRealtimeClipMovedMessage {
  type: "clip_moved";
  /** Repositioned clip. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
  /** Queue containing the clip: generation or playout. */

  queue: string;
  /** Resulting position, 0 = front. */

  position: number;
}

/** Emitted when generation fails; the clip is removed and the queue moves on. */
export interface H3ReferenceToVideoTurboRealtimeClipFailedMessage {
  type: "clip_failed";
  /** Failed clip. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
  /** Why generation failed. */

  reason: string;
}

/** Emitted as the correlated reply when pop removes a queued clip. */
export interface H3ReferenceToVideoTurboRealtimeClipPoppedMessage {
  type: "clip_popped";
  /** Removed clip; an in-flight result will be discarded. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
}

/** Emitted as the correlated reply when enqueue accepts a clip. */
export interface H3ReferenceToVideoTurboRealtimeClipQueuedMessage {
  type: "clip_queued";
  /** Accepted clip, including its UUID; ready is false. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
}

/** Emitted when a clip starts sending to the output tracks. */
export interface H3ReferenceToVideoTurboRealtimeClipStartedMessage {
  type: "clip_started";
  /** Clip now playing. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
}

/** Emitted when stop or reset cuts a clip; it cannot be resumed. */
export interface H3ReferenceToVideoTurboRealtimeClipStoppedMessage {
  type: "clip_stopped";
  /** Interrupted clip. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
  /** Total seconds sent in the session. */

  seconds_sent: number;
}

/** Emitted on connect and queue changes; also answers get_queue. */
export interface H3ReferenceToVideoTurboRealtimeQueueUpdateMessage {
  type: "queue_update";
  /** Always empty for Ref2VA; no tail frames or replayable history are retained. */

  history: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number }[];
  /** Built clips ready to play, front first. */

  playout: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number }[];
  /** Waiting/in-flight builds, front first. */

  generation: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number }[];
}

/** Emitted on connect and after session state changes; also answers get_state. */
export interface H3ReferenceToVideoTurboRealtimeStateUpdateMessage {
  type: "state_update";
  /** Next automatically assigned seed. */

  seed: number;
  /** Output video width in pixels. */

  width: number;
  /** Session aspect ratio. */

  aspect: string;
  /** Output video height in pixels. */

  height: number;
  /** A clip is armed or playing on the output tracks. */

  playing: boolean;
  /** Ready clips start automatically when idle. */

  autoplay: boolean;
  /** Actual duration used by enqueues without their own seconds. */

  clip_seconds: number;
  /** Clips finished or stopped during this session. */

  clips_played: number;
  /** Seconds sent on the tracks during this session. */

  seconds_sent: number;
  /** Ready clips waiting to play. */

  playout_queued: number;
  /** Commands permitted by current queue/playback state; their arguments still need validation. */

  valid_commands: string[];
  /** Playing clip UUID, or null when idle. */

  playing_clip_id: string | null;
  /** Maximum accepted requested duration. */

  clip_seconds_max: number;
  /** Minimum accepted requested duration. */

  clip_seconds_min: number;
  /** Maximum ready queue size; building pauses while full. */

  playout_capacity: number;
  /** True flushes to black at boundaries; false holds the last frame and avoids flushing between ready autoplay clips. */

  flush_on_clip_end: boolean;
  /** Clips in the generation queue, including the running build. */

  generation_queued: number;
  /** Maximum generation queue size. */

  generation_capacity: number;
}

/** Emitted when all frames and synchronized audio have been sent. */
export interface H3ReferenceToVideoTurboRealtimeClipFinishedMessage {
  type: "clip_finished";
  /** Completed clip. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
  /** Total seconds sent in the session, including this clip. */

  seconds_sent: number;
}

/** Emitted when a command is refused without changing the queue/defaults. */
export interface H3ReferenceToVideoTurboRealtimeCommandErrorMessage {
  type: "command_error";
  /** Why the command was refused. */

  reason: string;
  /** Refused command name. */

  command: string;
}

/** Emitted as the correlated reply when set_seed is accepted. */
export interface H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage {
  type: "seed_accepted";
  /** Next automatically assigned seed. */

  seed: number;
}

/** Emitted as the correlated reply when reset clears the playlist and defaults. */
export interface H3ReferenceToVideoTurboRealtimeSessionResetMessage {
  type: "session_reset";
  /** Whether reset cut an armed or playing clip. */

  was_playing: boolean;
  /** Clips removed from both queues, excluding the playing clip. */

  cleared_clips: number;
}

/** Emitted when a build enters the playout queue. */
export interface H3ReferenceToVideoTurboRealtimeClipGeneratedMessage {
  type: "clip_generated";
  /** Built clip, ready to play. */

  clip: { "seed": number; "ready": boolean; "frames": number; "prompt": string; "clip_id": string; "seconds": number; "metadata": string; "has_reference_image"?: boolean; "reference_image_count"?: number };
}

/** Emitted as the correlated reply when set_flush_on_clip_end is accepted. */
export interface H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage {
  type: "flush_accepted";
  /** Whether clip boundaries flush the output to black. */

  enabled: boolean;
}

/** Emitted as the correlated reply when set_canvas is accepted. */
export interface H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage {
  type: "canvas_accepted";
  /** Video width in pixels. */

  width: number;
  /** Accepted aspect ratio. */

  aspect: string;
  /** Video height in pixels. */

  height: number;
}

/** Emitted as the correlated reply when set_autoplay is accepted. */
export interface H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage {
  type: "autoplay_accepted";
  /** Whether ready clips start automatically. */

  enabled: boolean;
}

/** Emitted as the correlated reply when set_clip_seconds is accepted. */
export interface H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage {
  type: "clip_length_accepted";
  /** Effective default frame count. */

  frames: number;
  /** Effective default duration, in seconds. */

  clip_seconds: number;
}

export type H3ReferenceToVideoTurboRealtimeMessage =
  | H3ReferenceToVideoTurboRealtimeClipMovedMessage
  | H3ReferenceToVideoTurboRealtimeClipFailedMessage
  | H3ReferenceToVideoTurboRealtimeClipPoppedMessage
  | H3ReferenceToVideoTurboRealtimeClipQueuedMessage
  | H3ReferenceToVideoTurboRealtimeClipStartedMessage
  | H3ReferenceToVideoTurboRealtimeClipStoppedMessage
  | H3ReferenceToVideoTurboRealtimeQueueUpdateMessage
  | H3ReferenceToVideoTurboRealtimeStateUpdateMessage
  | H3ReferenceToVideoTurboRealtimeClipFinishedMessage
  | H3ReferenceToVideoTurboRealtimeCommandErrorMessage
  | H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage
  | H3ReferenceToVideoTurboRealtimeSessionResetMessage
  | H3ReferenceToVideoTurboRealtimeClipGeneratedMessage
  | H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage
  | H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage
  | H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage
  | H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage;

/**
 * Options for creating a H3ReferenceToVideoTurboRealtimeModel (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type H3ReferenceToVideoTurboRealtimeOptions = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the H3ReferenceToVideoTurboRealtime model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class H3ReferenceToVideoTurboRealtimeModel extends Reactor {
  constructor(options?: H3ReferenceToVideoTurboRealtimeOptions) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...H3ReferenceToVideoTurboRealtimeTracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /**
   * Remove a clip from its queue; reply clip_popped and emit queue_update and state_update. A running build finishes but is discarded. Refuses with command_error for a missing/unknown id. Use stop for the playing clip.
   * @param params - Remove a clip from its queue; reply clip_popped and emit queue_update and state_update. A running build finishes but is discarded. Refuses with command_error for a missing/unknown id. Use stop for the playing clip.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeClipPoppedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async pop(params: H3ReferenceToVideoTurboRealtimePopParams): Promise<H3ReferenceToVideoTurboRealtimeClipPoppedMessage | undefined> {
    const reply = await this.sendCommand("pop", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipPoppedMessage>(reply);
  }

  /**
   * Reposition within the current queue, 0 = front. A running build is unaffected. Replies clip_moved and emits queue_update; refuses with command_error for a missing/unknown id or invalid position.
   * @param params - Reposition within the current queue, 0 = front. A running build is unaffected. Replies clip_moved and emits queue_update; refuses with command_error for a missing/unknown id or invalid position.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeClipMovedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async move(params: H3ReferenceToVideoTurboRealtimeMoveParams): Promise<H3ReferenceToVideoTurboRealtimeClipMovedMessage | undefined> {
    const reply = await this.sendCommand("move", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipMovedMessage>(reply);
  }

  /**
   * Play the front ready clip, or a named ready clip. Consumes it and emits clip_started, queue_update and state_update. Refuses with command_error if already playing or no matching ready clip exists.
   * @param params - Play the front ready clip, or a named ready clip. Consumes it and emits clip_started, queue_update and state_update. Refuses with command_error if already playing or no matching ready clip exists.
   * @returns Resolves once the model's handler has completed; this command declares no reply payload.
   */

  async play(params: H3ReferenceToVideoTurboRealtimePlayParams): Promise<undefined> {
    await this.sendCommand("play", params);
    return undefined;
  }

  /**
   * Cut playback and emit clip_stopped and state_update; queues are untouched. Under autoplay this skips to the next clip. Refuses with command_error when nothing is playing.
   * @returns Resolves once the model's handler has completed; this command declares no reply payload.
   */

  async stop(): Promise<undefined> {
    await this.sendCommand("stop", {});
    return undefined;
  }

  /**
   * Drop both queues, cut playback, restore defaults and clear tracks. Replies session_reset; emits queue_update, state_update and clip_stopped if playing. In-flight results are discarded.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeSessionResetMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async reset(): Promise<H3ReferenceToVideoTurboRealtimeSessionResetMessage | undefined> {
    const reply = await this.sendCommand("reset", {});
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeSessionResetMessage>(reply);
  }

  /**
   * Queue a clip with 1–9 reference images at position, or at the back. Each clip keeps its own prompt and ordered references: new images do not alter earlier requests. The images guide appearance, not a fixed first or last frame. Replies clip_queued and broadcasts queue_update and state_update; completion emits clip_generated. Refuses with command_error for empty text, missing/invalid reference, invalid parameters or a full generation queue.
   * @param params - Queue a clip with 1–9 reference images at position, or at the back. Each clip keeps its own prompt and ordered references: new images do not alter earlier requests. The images guide appearance, not a fixed first or last frame. Replies clip_queued and broadcasts queue_update and state_update; completion emits clip_generated. Refuses with command_error for empty text, missing/invalid reference, invalid parameters or a full generation queue.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeClipQueuedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async enqueue(params: H3ReferenceToVideoTurboRealtimeEnqueueParams): Promise<H3ReferenceToVideoTurboRealtimeClipQueuedMessage | undefined> {
    const reply = await this.sendCommand("enqueue", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipQueuedMessage>(reply);
  }

  /**
   * Set the advancing default seed for future enqueues. Replies seed_accepted and emits state_update; an invalid seed emits command_error. Explicit per-clip seeds do not advance it.
   * @param params - Set the advancing default seed for future enqueues. Replies seed_accepted and emits state_update; an invalid seed emits command_error. Explicit per-clip seeds do not advance it.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setSeed(params: H3ReferenceToVideoTurboRealtimeSetSeedParams): Promise<H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage | undefined> {
    const reply = await this.sendCommand("set_seed", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage>(reply);
  }

  /**
   * Reply queue_update with both queues in full. The history field is empty: Ref2VA retains no continuation frames. Valid at any time.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeQueueUpdateMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async getQueue(): Promise<H3ReferenceToVideoTurboRealtimeQueueUpdateMessage | undefined> {
    const reply = await this.sendCommand("get_queue", {});
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeQueueUpdateMessage>(reply);
  }

  /**
   * Reply state_update with defaults, capacities, playback progress and valid_commands. Valid at any time.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeStateUpdateMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async getState(): Promise<H3ReferenceToVideoTurboRealtimeStateUpdateMessage | undefined> {
    const reply = await this.sendCommand("get_state", {});
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeStateUpdateMessage>(reply);
  }

  /**
   * Set the canvas while both queues and playback are empty. Replies canvas_accepted and emits state_update; refuses with command_error for an unsupported aspect or nonempty session.
   * @param params - Set the canvas while both queues and playback are empty. Replies canvas_accepted and emits state_update; refuses with command_error for an unsupported aspect or nonempty session.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setCanvas(params: H3ReferenceToVideoTurboRealtimeSetCanvasParams): Promise<H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage | undefined> {
    const reply = await this.sendCommand("set_canvas", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage>(reply);
  }

  /**
   * Automatically play ready clips whenever idle. Empty queues wait; no prompts are generated automatically. Replies autoplay_accepted and emits state_update.
   * @param params - Automatically play ready clips whenever idle. Empty queues wait; no prompts are generated automatically. Replies autoplay_accepted and emits state_update.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setAutoplay(params: H3ReferenceToVideoTurboRealtimeSetAutoplayParams): Promise<H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage | undefined> {
    const reply = await this.sendCommand("set_autoplay", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage>(reply);
  }

  /**
   * Set the duration for future enqueues, aligned to a supported frame count. Replies clip_length_accepted and emits state_update; invalid lengths emit command_error. Queued clips keep their lengths.
   * @param params - Set the duration for future enqueues, aligned to a supported frame count. Replies clip_length_accepted and emits state_update; invalid lengths emit command_error. Queued clips keep their lengths.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setClipSeconds(params: H3ReferenceToVideoTurboRealtimeSetClipSecondsParams): Promise<H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage | undefined> {
    const reply = await this.sendCommand("set_clip_seconds", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage>(reply);
  }

  /**
   * Choose black or a held last frame at boundaries. Off carries the playback clock across ready autoplay clips without flushing. Does not guarantee visual continuity; reset always clears tracks. Replies flush_accepted and emits state_update.
   * @param params - Choose black or a held last frame at boundaries. Off carries the playback clock across ready autoplay clips without flushing. Does not guarantee visual continuity; reset always clears tracks. Replies flush_accepted and emits state_update.
   * @returns The correlated {@link H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage} reply, or `undefined` when the send fails (the SDK never rejects — see `getLastError()`).
   */

  async setFlushOnClipEnd(params: H3ReferenceToVideoTurboRealtimeSetFlushOnClipEndParams): Promise<H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage | undefined> {
    const reply = await this.sendCommand("set_flush_on_clip_end", params);
    return reply === undefined ? undefined : _unwrapMessage<H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage>(reply);
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated H3ReferenceToVideoTurboRealtimeMessage
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: H3ReferenceToVideoTurboRealtimeMessage) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<H3ReferenceToVideoTurboRealtimeMessage>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "clip_moved" messages only.
   * @returns Unsubscribe function
   */

  onClipMoved(handler: (message: H3ReferenceToVideoTurboRealtimeClipMovedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_moved") handler(msg as H3ReferenceToVideoTurboRealtimeClipMovedMessage);
    });
  }

  /**
   * Subscribe to "clip_failed" messages only.
   * @returns Unsubscribe function
   */

  onClipFailed(handler: (message: H3ReferenceToVideoTurboRealtimeClipFailedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_failed") handler(msg as H3ReferenceToVideoTurboRealtimeClipFailedMessage);
    });
  }

  /**
   * Subscribe to "clip_popped" messages only.
   * @returns Unsubscribe function
   */

  onClipPopped(handler: (message: H3ReferenceToVideoTurboRealtimeClipPoppedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_popped") handler(msg as H3ReferenceToVideoTurboRealtimeClipPoppedMessage);
    });
  }

  /**
   * Subscribe to "clip_queued" messages only.
   * @returns Unsubscribe function
   */

  onClipQueued(handler: (message: H3ReferenceToVideoTurboRealtimeClipQueuedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_queued") handler(msg as H3ReferenceToVideoTurboRealtimeClipQueuedMessage);
    });
  }

  /**
   * Subscribe to "clip_started" messages only.
   * @returns Unsubscribe function
   */

  onClipStarted(handler: (message: H3ReferenceToVideoTurboRealtimeClipStartedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_started") handler(msg as H3ReferenceToVideoTurboRealtimeClipStartedMessage);
    });
  }

  /**
   * Subscribe to "clip_stopped" messages only.
   * @returns Unsubscribe function
   */

  onClipStopped(handler: (message: H3ReferenceToVideoTurboRealtimeClipStoppedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_stopped") handler(msg as H3ReferenceToVideoTurboRealtimeClipStoppedMessage);
    });
  }

  /**
   * Subscribe to "queue_update" messages only.
   * @returns Unsubscribe function
   */

  onQueueUpdate(handler: (message: H3ReferenceToVideoTurboRealtimeQueueUpdateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "queue_update") handler(msg as H3ReferenceToVideoTurboRealtimeQueueUpdateMessage);
    });
  }

  /**
   * Subscribe to "state_update" messages only.
   * @returns Unsubscribe function
   */

  onStateUpdate(handler: (message: H3ReferenceToVideoTurboRealtimeStateUpdateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "state_update") handler(msg as H3ReferenceToVideoTurboRealtimeStateUpdateMessage);
    });
  }

  /**
   * Subscribe to "clip_finished" messages only.
   * @returns Unsubscribe function
   */

  onClipFinished(handler: (message: H3ReferenceToVideoTurboRealtimeClipFinishedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_finished") handler(msg as H3ReferenceToVideoTurboRealtimeClipFinishedMessage);
    });
  }

  /**
   * Subscribe to "command_error" messages only.
   * @returns Unsubscribe function
   */

  onCommandError(handler: (message: H3ReferenceToVideoTurboRealtimeCommandErrorMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "command_error") handler(msg as H3ReferenceToVideoTurboRealtimeCommandErrorMessage);
    });
  }

  /**
   * Subscribe to "seed_accepted" messages only.
   * @returns Unsubscribe function
   */

  onSeedAccepted(handler: (message: H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "seed_accepted") handler(msg as H3ReferenceToVideoTurboRealtimeSeedAcceptedMessage);
    });
  }

  /**
   * Subscribe to "session_reset" messages only.
   * @returns Unsubscribe function
   */

  onSessionReset(handler: (message: H3ReferenceToVideoTurboRealtimeSessionResetMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "session_reset") handler(msg as H3ReferenceToVideoTurboRealtimeSessionResetMessage);
    });
  }

  /**
   * Subscribe to "clip_generated" messages only.
   * @returns Unsubscribe function
   */

  onClipGenerated(handler: (message: H3ReferenceToVideoTurboRealtimeClipGeneratedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_generated") handler(msg as H3ReferenceToVideoTurboRealtimeClipGeneratedMessage);
    });
  }

  /**
   * Subscribe to "flush_accepted" messages only.
   * @returns Unsubscribe function
   */

  onFlushAccepted(handler: (message: H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "flush_accepted") handler(msg as H3ReferenceToVideoTurboRealtimeFlushAcceptedMessage);
    });
  }

  /**
   * Subscribe to "canvas_accepted" messages only.
   * @returns Unsubscribe function
   */

  onCanvasAccepted(handler: (message: H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "canvas_accepted") handler(msg as H3ReferenceToVideoTurboRealtimeCanvasAcceptedMessage);
    });
  }

  /**
   * Subscribe to "autoplay_accepted" messages only.
   * @returns Unsubscribe function
   */

  onAutoplayAccepted(handler: (message: H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "autoplay_accepted") handler(msg as H3ReferenceToVideoTurboRealtimeAutoplayAcceptedMessage);
    });
  }

  /**
   * Subscribe to "clip_length_accepted" messages only.
   * @returns Unsubscribe function
   */

  onClipLengthAccepted(handler: (message: H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "clip_length_accepted") handler(msg as H3ReferenceToVideoTurboRealtimeClipLengthAcceptedMessage);
    });
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }

  /**
   * Subscribe to the "main_audio" recvonly audio track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainAudio(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_audio") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
