"use client";

// Short names for the generated client.
//
// `h3.ts` and `h3.react.tsx` are generated by @reactor-team/codegen from the
// model's published schema and carry its full name in every symbol
// (`useH3ReferenceToVideoTurboRealtimeStateUpdate`). Those are the names the
// typed npm package will export when it ships, so they are the real ones —
// this file only shortens them at the import boundary so the components stay
// readable. Nothing here adds behaviour.

import type { FileRef } from "@reactor-team/js-sdk";

export {
  H3ReferenceToVideoTurboRealtimeProvider as H3Provider,
  H3ReferenceToVideoTurboRealtimeMainVideoView as H3MainVideoView,
  useH3ReferenceToVideoTurboRealtime as useH3,
  useH3ReferenceToVideoTurboRealtimeStateUpdate as useH3StateUpdate,
  useH3ReferenceToVideoTurboRealtimeQueueUpdate as useH3QueueUpdate,
  useH3ReferenceToVideoTurboRealtimeClipStarted as useH3ClipStarted,
  useH3ReferenceToVideoTurboRealtimeClipGenerated as useH3ClipGenerated,
  useH3ReferenceToVideoTurboRealtimeClipFailed as useH3ClipFailed,
  useH3ReferenceToVideoTurboRealtimeCommandError as useH3CommandError,
} from "./h3.react";

export type {
  H3ReferenceToVideoTurboRealtimeStateUpdateMessage as H3State,
  H3ReferenceToVideoTurboRealtimeQueueUpdateMessage as H3Queue,
  H3ReferenceToVideoTurboRealtimeEnqueueParams as H3EnqueueParams,
} from "./h3";

/** One entry in a `queue_update` array, and the shape carried by clip messages. */
export type H3Clip = {
  clip_id: string;
  prompt: string;
  metadata: string;
  frames: number;
  seconds: number;
  seed: number;
  ready: boolean;
  has_reference_image?: boolean;
  reference_image_count?: number;
};

/** The aspects `set_canvas` accepts. */
export type H3Aspect = "16:9" | "1:1" | "9:16" | "4:3";

/** The four canvases the model accepts, with the pixels each one produces. */
export const CANVASES: ReadonlyArray<{
  aspect: H3Aspect;
  width: number;
  height: number;
}> = [
  { aspect: "16:9", width: 1344, height: 768 },
  { aspect: "1:1", width: 768, height: 768 },
  { aspect: "9:16", width: 768, height: 1344 },
  { aspect: "4:3", width: 1024, height: 768 },
];

/** Per-clip reference count the model accepts. */
export const MAX_REFERENCES = 9;
/** Prompt ceiling the model accepts. */
export const MAX_PROMPT_CHARS = 12_000;

// Build the `reference_images` value for `enqueue`.
//
// This is the one place the two upload paths differ, and getting it wrong
// fails silently — the command is accepted locally and refused by the model.
//
// A *single* `reference_image` is passed as a `FileRef` and needs no help: the
// SDK walks the command's top-level values, lifts any `FileRef` out into a
// separate upload slot, and the runtime resolves it from there.
//
// A *list* is not walked. The SDK only inspects top-level values, so an array
// is left in the JSON payload as-is, and a `FileRef` serialized as JSON comes
// out with `uploadId`/`mimeType` — not what the model reads. The model expects
// `reference_images: [{ upload_id }, …]` in the payload and resolves each id
// itself, so that is the shape to send.
//
// The generated client types this parameter as `FileRef[]`, which is why the
// cast lives here. Keep it in this one function rather than at each call site.
export function toReferenceImages(refs: readonly FileRef[]): FileRef[] {
  return refs.map((ref) => ({
    upload_id: ref.uploadId,
  })) as unknown as FileRef[];
}
